#!/bin/bash

docker build -t cihm-ingestwip . &&
  docker run -it -v $(pwd)/CIHM-Meta:/home/tdr/CIHM-Meta -v $(pwd)/CIHM-TDR:/home/tdr/CIHM-TDR -v "/etc/canadiana/tdr.conf:/home/tdr/tdr.conf" -v "/var/log/tdr:/var/log/tdr" -v "/var/lock/tdr:/var/lock/tdr" -v "/data/tempingest:/home/tdr/tempIngest"  cihm-ingestwip tdr bash
